### ISSUE TITLE
Flutter Applications Crash

### ISSUE THREAD

**Issue by moneer-muntazah** [k-paxian/dart-json-mapper#115]
Hi k-paxian,

Hope you are doing well.

There is something about the package that makes flutter applications crash both on Android and iOS. **This only happens with the AOT build. the JIT build works without issues** so you'll need to run `flutter build android` or `flutter build ios` Here is a minimal application to reproduce. I left **main.mapper.g.dart** file just in case. 

https://github.com/moneer-muntazah/json_mapper_build_bug

Here is my `flutter doctor -v`

```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.804], locale en-US)
    • Flutter version 1.22.6 at C:\flutter
    • Framework revision 9b2d32b605 (4 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\Moneer\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\Moneer\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\Moneer\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (1 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.

```

I downgraded from `1.7.10` to `1.7.6` and the application ran.

Thank you

**Comment by moneer-muntazah** [comment]
One more thing if I may. I keep getting `null` as the value of the `id` in the example project above. Even after including `processAnnotatedMembersOnly: true` to `DeserializationOptions` in the `fromJson` method invocation. It's only after I add a scheme that it works, and I get the value `42` am I doing something wrong there? Would you please look into that as well?

Thank you

**Comment by k-paxian** [comment]
The second one is easy, you have:

```dart
@jsonSerializable
@Json(name: 'MyModule') // <= this one is the problem
class MyModule {
  @JsonProperty(name: 'my_id')
  int id;
}
```

```json
 { "my_id": 42 } 
```

Whereas, if you really need this to work you should remove `@Json(name: 'MyModule')` OR modify your json as:

```json
{
"MyModule": { "my_id": 42 }
}
```

**Comment by k-paxian** [comment]
For the build crash, could you please reproduce it with the flutter for web build, this way it's easier to debug. I'm pretty sure if it'll work for web it'll work for android/ios as well. I'm not able to build for ios, since I don't have a mac.

And please include crash traces or something helpful. I've tried your project with the `flutter build web` and has no issues running it off the chrome via JIT and or AOT build.

**Comment by moneer-muntazah** [comment]
I tried web with the beta channel and it worked without issues. I also built it for android with beta, and it still crashed  just like it did with the stable channel. The logcat says this every time the app crashes. There are many details, but I think this is significant.

```
02-22 09:00:50.857  6471  6471 F DEBUG   : Timestamp: 2021-02-22 09:00:50+0300
02-22 09:00:50.857  6471  6471 F DEBUG   : pid: 6434, tid: 6461, name: 1.ui  >>> com.moneer.json_mapper_build_bug <<<
02-22 09:00:50.857  6471  6471 F DEBUG   : uid: 10151
02-22 09:00:50.857  6471  6471 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x53
02-22 09:00:50.857  6471  6471 F DEBUG   : Cause: null pointer dereference
02-22 09:00:50.857  6471  6471 F DEBUG   :     rax 0000000000000054  rbx 00007e6901e94599  rcx 0000000000000054  rdx 00007e6901e8eac9
02-22 09:00:50.857  6471  6471 F DEBUG   :     r8  00007e6902188f11  r9  00007e6903008041  r10 00007e690300abc1  r11 0000000000000000
02-22 09:00:50.857  6471  6471 F DEBUG   :     r12 00007e6903008041  r13 00007e69020b8708  r14 00007e6a9c9b0aa0  r15 00007e6945500041
02-22 09:00:50.857  6471  6471 F DEBUG   :     rdi 00007e6903008041  rsi 00007e6902188f11
02-22 09:00:50.857  6471  6471 F DEBUG   :     rbp 00007e6903c48448  rsp 00007e6903c483c8  rip 00007e69036ba97f
02-22 09:00:50.857  6471  6471 F DEBUG   : backtrace:
02-22 09:00:50.857  6471  6471 F DEBUG   :       #00 pc 00000000000fa97f  /data/app/~~fx1-mY0tF_nN1yjbwEZrEA==/com.moneer.json_mapper_build_bug-D4M_khRYYMdFy7KsmH04-g==/lib/x86_64/libapp.so (offset 0xf000) (_kDartIsolateSnapshotInstructions+964991) (BuildId: 95dc5951106120887347667b2ababcc1)
02-22 09:00:50.928     0     0 D logd    : logdr: UID=10151 GID=10151 PID=6471 n tail=50 logMask=8 pid=6434 start=0ns timeout=0ns
02-22 09:00:50.932     0     0 D logd    : logdr: UID=10151 GID=10151 PID=6471 n tail=50 logMask=1 pid=6434 start=0ns timeout=0ns
02-22 09:00:51.082     0     0 D logd    : logdr: UID=10151 GID=10151 PID=6471 n tail=0 logMask=8 pid=6434 start=0ns timeout=0ns
02-22 09:00:51.083     0     0 D logd    : logdr: UID=10151 GID=10151 PID=6471 n tail=0 logMask=1 pid=6434 start=0ns timeout=0ns
```

I tried with different commits, and the problem only starts with `c0f6e824d6ce6953921fee66b6aa40a6b259f9e6`
The generated mapper file is not the problem as it is identical to the previous commit. I hope this helps. Please let me know of any diagnostic method I can use to help further, and thank you for the second issue it totally slipped my

**Comment by k-paxian** [comment]
Thank you so much, that was enough to get to the root cause. Please evaluate `1.7.11` and let me know if something works 😄

**Comment by moneer-muntazah** [comment]
Yeah, it's fixed now. Just out of curiosity what was the language feature that caused this? I try reading through your code sometimes, but it's all Greek to me  😅

**Comment by k-paxian** [comment]
I hope someday to make the code base more readable, when it'll be stable enough and feature complete, which I think is pretty close. The next major milestone is the #97 which potentially eliminates issues like that at the root level.

It was a *not quite obvious* "null pointer issue", since it was:  

- OK on unit tests, they were green ✔️ 
- OK when compiled down to Web over AOT ✔️ 
- But... Failing on android / ios AOT 🔴 

So the place were [here](https://github.com/k-paxian/dart-json-mapper/commit/43c4404b5afd88bac24398d6090031fd76829486#diff-0a8af651b5a494df9abeea9f54a4a8303e38529cb90b0a61963fbdea47fa313eL473) 
`meta`  was `null`

and [here](https://github.com/k-paxian/dart-json-mapper/commit/43c4404b5afd88bac24398d6090031fd76829486#diff-c5ad7ad37f663c91f5e985d79a7de146b05215b8cc80d1725a3a5189b4fe6156L181)
`jsonProperty ` was `null`

And this parts came through some optimization during AOT prod build which caused real null pointer on binary level then.
So that's why this "nullsafe" support is so needed and long awaited improvement on the language itself.
