### ISSUE TITLE
Very slow deserialization relative to `dart:convert`

### ISSUE THREAD

**Issue by gavv** [k-paxian/dart-json-mapper#133]
Hi! Thanks for this great library!

I'm now experimenting with it and trying to adopt it to my project.

For now I use it only in tests. I noticed that in my use case, deserialization is for some reason very slow: 150-160ms and more for a rather small json file less than 1KB. For comparison, `dart:convert` decodes the same json to map by 150 μs (i.e. 1000x faster).

I've created an example flutter project that reproduces the issue: https://github.com/gavv/dart_json_mapper_example

Here are models: https://github.com/gavv/dart_json_mapper_example/blob/main/lib/models.dart

Here is a test with the JSON: https://github.com/gavv/dart_json_mapper_example/blob/main/test/json_test.dart

I've generated the code as follows:

```
flutter pub run build_runner build --delete-conflicting-outputs
```

And here is how you can run the test:

```
flutter test -r expanded
```

Output:

```
00:00 +0: dart_json_mapper
deserialize() executed in 203625 μs
deserialize() executed in 149071 μs
deserialize() executed in 160270 μs
deserialize() executed in 216924 μs
deserialize() executed in 170302 μs
deserialize() executed in 147884 μs
deserialize() executed in 151037 μs
deserialize() executed in 147463 μs
deserialize() executed in 150105 μs
deserialize() executed in 148412 μs
00:01 +1: dart_convert
deserialize() executed in 170 μs
deserialize() executed in 112 μs
deserialize() executed in 140 μs
deserialize() executed in 128 μs
deserialize() executed in 120 μs
deserialize() executed in 123 μs
deserialize() executed in 133 μs
deserialize() executed in 125 μs
deserialize() executed in 122 μs
deserialize() executed in 135 μs
00:01 +2: All tests passed!
```

I'm running tests on 64-bit Linux with Intel Core i7 2.70GHz.

```
Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (7 days ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0
```

**Comment by k-paxian** [comment]
Thank you for giving it a chance at least, I'm sorry to disappoint you 😒 but this [test ](https://github.com/k-paxian/dart-json-mapper/tree/master/perf-test/test/starlink) shows exactly what you've mentioned.

If you need fastest possible performance & cluttered/duplicated code you have plenty of alternative options
* `dart:convert`
* `json_serializable` 
* `built_value`

This library was aimed to solve cluttered & cumbersome nature of other solutions. Surely it's more upside for optimizations, anyway eventually it will be slower than mentioned alternatives due to limitations of chosen architecture. The main architectural difference is **dynamic**  approach instead of **fully static** approaches. Dynamic decisions in runtime requires time unfortunately.  

`dart:convert` is super appropriate if you have a few tiny & simple json needs, but when you have hundreds of classes with complex hierarchies it will not cover all the use cases, it will be fast + a bunch of hand made custom code you'll throw on top of it, which you'll need to maintain & support in future.

Indeed, there is a price to pay for a clean code

**Comment by gavv** [comment]
BTW, maybe taking a look at go(lang) json serializer may give some inspiration on possible optimizations. IIRC, when you're using a type Foo first time (at runtime), they resolve all dynamic stuff and then create a specialized encoder/decoder for Foo and store in in a global cache. Subsequent serialization of values of the same type are then much faster.

**Comment by k-paxian** [comment]
since `2.1.1` should be a bit faster. I'll continue optimizations whenever opportunity comes towards my way. Thank you for your time contribution.

**Comment by k-paxian** [comment]
btw, with [those](https://github.com/k-paxian/dart-json-mapper/pull/176) optimizations, things improved a bit.
