### ISSUE TITLE
Problems with dart obfuscation

### ISSUE THREAD

**Issue by RaviKavaiya** [k-paxian/dart-json-mapper#57]
Hi, thanks for this nice library. 

In one application, everything was running fine and perfect when I was developing. Had several model classes, all perfect.

But problems started arriving when I just ran my app in Profile (and Release) mode on a physical device. None of my model class was getting deserialized. I tried many times but was getting a weird error like 
`Unhandled Exception: NoSuchCapabilityError: no capability to invoke the constructor ""` and some long log. 

After digging for 2 hours, I came to know that I was using this: `extra-gen-snapshot-options=--obfuscate`. That was the problem. I enabled it long ago and didn't remember :)

My question is, is there any solution to get dart_json_mapper working with obfuscation??
I know that this is not your library's fault (and obfuscation is also not a necessary thing, but still...).

**Comment by k-paxian** [comment]
Thank you for raising this, I guess this would be the first serious limitation for "reflective" approach, since it's solely targeting Dart objects topology based on "name" identifiers which will be lost after obfuscation.

Unfortunately, cannot see a clean solution to that at the moment.

It's a good time for you to rethink your choice for this library. In case obfuscation is a *must* for your application. You should look into built_value or json_serializable libraries for that.

I'll update the docs to mention this as a limitation of using this library to give a heads up for the developers.

**Comment by RaviKavaiya** [comment]
@k-paxian I guess obfuscation is not mandatory for me (was never in the past, too!).

Regarding thinking of other libraries, I am never gonna do that. You know why ;) This library is just I always wanted, has tons of features that I couldn't find in other libraries.

Thanks.
