### ISSUE TITLE
[Suggestion] Provide custom value to enum

### ISSUE THREAD

**Issue by AntiqPeace** [k-paxian/dart-json-mapper#58]
Currently, the `enum` values are converted to String when calling `toMap()`. But, I want to convert these values into integeres.

Similar to `json_serializable`, can there be functionality, like `@JsonValue`?. So that we can provide custom values to enums.

e.g.,
```dart
@JsonProperty()
enum MyEnum {
  @JsonValue(0)
  value1,
  @JsonValue(1)
  value2
}
```

Sure, we can write custom converters for the same. But, I have dozens of such enums and don't want to write converter for all

Thanks...

**Comment by k-paxian** [comment]
No problem,

What if you'll use a **single** converter for all `Enums`?  In case you are gonna assign all the values
sequential numbers. Here is a solution for that in [this](https://github.com/k-paxian/dart-json-mapper/commit/652fbfeb6b1c2254465ac1944b6a36ec09b028c9) commit. Literally you are passing generic converter for all Enums. 

First I would like to warn you on relying on value indexes, since suddenly someone could change the values order in enum declaration and persisted values will not be mapped back to proper values.

On the other hand, don't want to introduce non consistent solution targeting Enums. 
Not all enums could be annotated, lots of them are provided by third party packages, so `@JsonValue` approach will not be a silver bullet here.

**Comment by AntiqPeace** [comment]
@k-paxian  Thanks for your answer.
I want this functionality for all enums. (Use index for all enums).

So, if I understood correctly, I just need to use 
```dart
final adapter = JsonMapperAdapter(converters: {Enum: enumConverterNumeric});

JsonMapper().useAdapter(adapter);
```
only, right? That will apply numeric converter to all enums??

Thanks for such nice library.

**Comment by k-paxian** [comment]
Exactly!

**Comment by RaviKavaiya** [comment]
@k-paxian This method works for me. But, when I use `Scheme`s, doing the above thing didn't help me :(. It still converts to string.

When using Schemes, I have to pass the `converter` parameter to each `@JsonProperty` manually.

**Comment by YouWillBe** [comment]
How to convert like this ?
```dart
const json = '''
{
    "color": "Blue"
}
''';
// it is "Blue" , instead of "Color.Blue"
```

```dart
enum Color { Red, Green, Blue }

class MyData {
    @JsonProperty(enumValues: Color.values, converter:???)
    Color color;
}
```

**Comment by k-paxian** [comment]
What's the goal? to have it like that for all Enums? or just single field?

**Global**
```dart
JsonMapper().useAdapter(JsonMapperAdapter(converters: {Enum: enumConverterShort}));
```

**Local**
```dart
class MyData {
    @JsonProperty(enumValues: Color.values, converter: enumConverterShort)
    Color color;
}
```

**Comment by YouWillBe** [comment]
> What's the goal? to have it like that for all Enums? or just single field?
> 
> **Global**
> 
> ```dart
> JsonMapper().useAdapter(JsonMapperAdapter(converters: {Enum: enumConverterShort}));
> ```
> 
> **Local**
> 
> ```dart
> class MyData {
>     @JsonProperty(enumValues: Color.values, converter: enumConverterShort)
>     Color color;
> }
> ```
> 
> Since **1.5.18** `enumConverterShort` is in the box, enjoy

Thanks for your response. It works fine.
