### ISSUE TITLE
Can you explain `build.yaml` in the `jsonexample`?

### ISSUE THREAD

**Issue by vinkaga** [k-paxian/dart-json-mapper#59]
build.yaml in the example contains the following builders
```dart
      reflectable:
        generate_for:
        - lib/main.dart
        - test/*_unit_test.dart
      built_value_generator|built_value:
        generate_for:
        - lib/built_value/*.dart
        options:
          header: |
            // Copyright 2018 The Chromium Authors. All rights reserved.
            // Use of this source code is governed by a BSD-style license that can be
            // found in the LICENSE file.

            // GENERATED CODE - DO NOT MODIFY BY HAND
      json_serializable:
        generate_for:
        - lib/json_serializable/*.dart
```
My questions are?

- What is the difference between `built_value_generator|built_value` and `json_serializable` builders?
- Is it possible to use multiple builders for a single project file? Or do you have the split the contents to separate file depending upon needed builder?

**Comment by k-paxian** [comment]
> What is the difference between built_value_generator|built_value and json_serializable builders?

Those two libraries are targeting boilerplate code generation, usually they produce `*.g.part.dart` files which later on included as parts to your project code base.

`build_value` has more responsibilities rather than plain serialization/deserialization, whereas 
`json_serializable` is responsible for serialization/deserialization **only**

> Is it possible to use multiple builders for a single project file? Or do you have the split the contents to separate file depending upon needed builder?

You can use all of them simultaneously, depends on your project specific needs.

**Comment by vinkaga** [comment]
Thank you.
