### ISSUE TITLE
ICustomConverter.fromJSON is called twice

### ISSUE THREAD

**Issue by fedotxxl** [k-paxian/dart-json-mapper#75]
Hello. I registered a custom converter for my Enum with `JsonMapperAdapter.converters` option. The problem is that method `fromJSON` is called twice:
The first time `jsonValue` param is the value from API
The second time `jsonValue` param is the value returned by the first call

Why is it called two times? I've got hackie solution to fix it (check jsonValue type) but it's a really hack which may not work in some cases. This leads to a pretty strange converter code

**Comment by k-paxian** [comment]
Could you please share your code illustrating the issue?

**Comment by fedotxxl** [comment]
Created https://github.com/fedotxxl/flutter-json-test - run it and check for "!" in the console - it should print only one "!"

**Comment by k-paxian** [comment]
> Why is it called two times? 

It is called twice because of fields intersection between constructor arguments and public fields.

* Initially converter invoked when constructor arguments are processed.
* Finally when instance is created using constructor, another pass is running over public class fields causing double converter invocation.

Case 1: No constructor provided. Public class fields only.  *[One call for converter per field should be expected]*
Case 2: Constructor provided, referencing **a subset** of class public fields as arguments. *[Double converter invocation issue here on intersected set of fields]*
Case 3: Constructor provided, referencing **all** class public fields as arguments. *[Double converter invocation issue here on intersected set of fields]*

As of version `1.5.19`:

Second pass for intersected set of fields should  not be performed.

Please let me know if this helps
